name: Playwright Tests with MCP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Playwright Tests with MCP
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      # Test website
      website:
        image: mcr.microsoft.com/playwright:v1.44.0-jammy
        ports:
          - 3000:3000
        volumes:
          - ${{ github.workspace }}:/app
        options: >-
          --workdir /app
          --entrypoint "/bin/sh"
          -c "npx serve -s . -l 3000"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      env:
        PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    - name: Start MCP server
      run: |
        npx @microsoft/playwright-mcp --port 7342 > mcp.log 2>&1 &
        echo "MCP_PID=$!" >> $GITHUB_ENV
        sleep 5  # Give MCP server time to start

    - name: Run Playwright tests with MCP
      run: npm run test:mcp
      env:
        BASE_URL: http://localhost:3000
        MCP_URL: http://localhost:7342

    - name: Stop MCP server
      if: always()
      run: |
        if [ -n "$MCP_PID" ]; then
          kill $MCP_PID || true
        fi
        
    - name: Show MCP server logs
      if: always()
      run: |
        echo "=== MCP Server Logs ==="
        cat mcp.log || true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test traces
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/
        retention-days: 30
